### PR TITLE
Fix wrong prop types

### LINKED ISSUE #88: Incorrect prop validation for template props
### Issue Type
bug report

#### Steps to Reproduce
Set any template prop

#### Current Behavior
Produces a warning in the console:
```console
[Vue warn]: Invalid prop: type check failed for prop "XXX". Expected Function, Object, got String
```

#### Expected Behavior
Now warnigns

### Environment Details
DevExtreme Vue v15.1.3-alpha.4

### LINKED ISSUE #100: Numberbox format property
### Issue Type
Bug report

### Description
I use dx-number-box in my project and initialize format property as a string (from devexpress documentation):
```
data: function () {
		return {
			numberbox: {
				value: 100.123,
				format: "$ #0.##",
			}
		}
}
```
The format is applying well but in the browser console I've got the red message::

> Invalid prop: type check failed for prop "format". Expected Object, got String.
>found in ---> <DxNumberBox> <Numberbox> at test\components\numberbox.vue

is it normal? or I do smth wrong?

### PR DESCRIPTION
**Pull request by lukyanovas**
Fix #100 Fix #88

### CODE REVIEW

File: tools/src/converter.ts [hunk 1]
```diff
@@ -13,6 +17,19 @@ function convertTypes(types: ITypeDescr[]): string[] {
...
+    let expandedTypes = [];
+    types.forEach((t) => {
+      if (t.isCustomType) {
+        const aliases = customTypes.filter((ct) => ct.name === t.type)[0].types;
+        if (aliases) {
+            expandedTypes = expandedTypes.concat(aliases);
+        }
+      }
+    });
+    return expandedTypes;
```
Comment (IlyaKhD) [inline tools/src/converter.ts]: What about this:
```
const expandedTypes = [];
...
expandedTypes.push(...aliases);
...
return expandedTypes;
```
It would be clearer, I think.

File: tools/src/generator.ts [hunk 2]
```diff
@@ -31,7 +31,8 @@ function generate(
   writeFile(out.indexFileName, generateIndex(modulePaths), { encoding: "utf8" });
 }
 
-function mapWidget(raw: IWidget, baseComponent: string): { fileName: string, component: IComponent } {
+function mapWidget(raw: IWidget, baseComponent: string, customTypes: ICustomType[]):
+ { fileName: string, component: IComponent } {
```
Comment (IlyaKhD) [inline tools/src/generator.ts]: I propose to make the return value declaration multiline:
```
): {
  fileName: string,
  component: IComponent
} {
```

File: tools/src/converter.ts [hunk 3]
```diff
@@ -13,6 +17,19 @@ function convertTypes(types: ITypeDescr[]): string[] {
     return Array.from(convertedTypes);
 }
 
+function expandTypes(types: ITypeDescr[], customTypes: ICustomType[]): ITypeDescr[] {
```
Comment (IlyaKhD) [inline tools/src/converter.ts]: Propose to make the `customTypes` a dictionary: `customTypes: Record<string, ICustomType>`
